#%RAML 1.0

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml
  errors: errors.raml
  headers: headers.raml
  queryParameters: queryParameters.raml

title: Individual Losses (MTD)
description: Provide a taxpayer’s financial data for their Brought Forward Losses and Loss Claims.
version: 3.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: application/json

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include docs/errors.md
 - title: Changelog
   content: !include docs/changelog.md
 - title: Support
   content: !include docs/support.md
 - title: Testing
   content: !include docs/testing.md

'/individuals/losses':
  /{nino}:
    uriParameters:
      nino:
        description: National Insurance number, in the format AA999999A.
        type: string
        example: TC663795B
    /brought-forward-losses:
      (annotations.group):
        name: Brought Forward Losses
        description: !include docs/group_broughtForwardLosses.md
      post: !include broughtForwardLosses_create.raml
      get: !include broughtForwardLosses_list.raml
      /{lossId}:
        uriParameters:
          lossId:
            description: A unique identifier for loss.<br><br>Must conform to the regular expression `^[A-Za-z0-9]{15}$`
            type: string
            example: "AAZZ1234567890a"
        get:  !include broughtForwardLosses_retrieve.raml
        /change-loss-amount:
          post: !include broughtForwardLosses_amend.raml
    /loss-claims:
      (annotations.group):
        name: Loss Claims
        description: !include docs/group_lossClaims.md
      post: !include lossClaimType_create.raml
      get: !include lossClaimType_list.raml
      /{claimId}:
        uriParameters:
          claimId:
            description: Unique identifier for the loss claim. Must conform to the regular expression ^[A-Za-z0-9]{15}$
            type: string
            example: "AAZZ0123456789a"
        get: !include lossClaimType_retrieve.raml
        /change-type-of-claim:
          post: !include lossClaimType_amend.raml