is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatLossId
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
displayName: Retrieve a Brought Forward Loss
description: This endpoint allows the developer to retrieve an existing brought forward loss amount. A National Insurance number and Loss must be provided.
(annotations.sandboxData): !include scenarios/broughtForwardLosses_retrieve.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
  200:
    body:
      application/json:
        type: !include schemas/broughtForwardLosses/retrieveBFLoss/retrieve_request.json
        examples:
          example-1:
            description: Self-employment Loss
            value: !include examples/broughtForwardLosses/retrieveBFLoss/retrieve_se_response.json
          example-2:
            description: UK Property Loss
            value: !include examples/broughtForwardLosses/retrieveBFLoss/retrieve_uk_property_response.json
          example-3:
            description: Foreign Property Loss
            value: !include examples/broughtForwardLosses/retrieveBFLoss/retrieve_foreign_property_response.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.
