is:
  - headers.acceptJson
  - headers.contentTypeJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTaxYear
  - errors.ruleTaxYearNotSupported
  - errors.ruleTaxYearRangeInvalid
  - errors.formatLossType
  - errors.formatTypeOfClaim
  - errors.formatBusinessId
  - errors.ruleTypeOfClaim400
  - errors.ruleDuplicateClaimSubmission
  - errors.ruleAccountingPeriodNotEnded
  - errors.ruleNoAccountingPeriod
  - errors.clientOrAgentNotAuthorised
  - errors.incorrectOrEmptyBody
  - errors.notFoundIncomeSource
displayName: Create a Loss Claim [test only]
description: This endpoint allows a developer to create a Loss Claim against an income source for a specific tax year. Claims cannot be made until after the End of Period Statement. A National Insurance number must be provided.
(annotations.sandboxData): !include scenarios/lossClaim_create.md
(annotations.scope): "write:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
body:
  application/json:
    description: The brought forward loss information brought into MTD
    type: !include schemas/lossClaims/createLC/create_request.json
    examples:
     example-1:
       description: Self-Employment Claim Request
       value: !include examples/lossClaims/createLC/create_request_self_employment_claim.json
     example-2:
       description: Property Claim Request
       value: !include examples/lossClaims/createLC/create_request_property_claim.json
responses:
  201:
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.
    body:
      application/json:
        type: !include schemas/lossClaims/createLC/create_response.json
        example: !include examples/lossClaims/createLC/create_response.json