is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTaxYear
  - errors.ruleTaxYearNotSupported
  - errors.ruleTaxYearRangeInvalid
  - errors.formatTypeOfClaim
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
  - errors.formatLossType
  - errors.formatBusinessId
  - queryParameters.taxYearClaimedFor
  - queryParameters.businessIdForClaims
  - queryParameters.typeOfLossForClaims
  - queryParameters.typeOfClaim
displayName: List Loss Claims [test only]
description: This endpoint allows a developer to retrieve the existing loss claims information. A National Insurance Number must be provided.
(annotations.sandboxData): !include scenarios/lossClaimType_list.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
  200:
    body:
      application/json:
        type: !include schemas/lossClaims/listLossClaims/list_response.json
        examples:
          example-1:
            description: Self-Employment Loss Claim
            value: !include examples/lossClaims/listLossClaims/list_response_self_employment_claims.json
          example-2:
            description: UK Property Loss Claim
            value: !include examples/lossClaims/listLossClaims/list_response_property_claims.json
          example-3:
             description: Foreign Property Loss Claim
             value: !include examples/lossClaims/listLossClaims/list_response_foreign_property_claims.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.