#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

traits:
  taxYearForClaims:
    queryParameters:
      taxYear:
        description: 'The tax year the data applies to, for example, 2019-20. The start year and end year must not span two tax years. No gaps are allowed, for example, 2019-21 is not valid. The minimum tax year is 2019-20.'
        example: "2019-20"
        required: false
  taxYearForBFLosses:
    queryParameters:
      taxYear:
        description: 'The tax year the data applies to, for example, 2018-19. The start year and end year must not span two tax years. No gaps are allowed, for example, 2018-20 is not valid. The minimum tax year is 2018-19.'
        example: "2018-19"
        required: false
  typeOfLossForClaims:
    queryParameters:
      typeOfLoss:
        description: 'The type of business the loss applies to.<br><br>Limited to the following possible values:<ul style = "list-style-type: none; padding: 0;"><li>`self-employment`<li>`uk-property-non-fhl`<li>`foreign-property`'
        required: false
  typeOfLossForBFLosses:
    queryParameters:
      typeOfLoss:
        description: 'The type of business the loss applies to.<br><br>Limited to the following possible values:<ul style = "list-style-type: none; padding: 0;"><li>`self-employment`<li>`uk-property-fhl`<li>`uk-property-non-fhl`<li>`foreign-property-fhl-eea`<li>`foreign-property`'
        required: false
  businessIdForClaims:
    queryParameters:
      businessId:
        description: 'The unique identifier of the income source the claim relates to.<br><br>Must conform to the regular expression `^X[A-Z0-9]{1}IS[0-9]{11}$`'
        example: 'XPIS00000001319'
        required: false
  businessIdForBFLosses:
    queryParameters:
      businessId:
        description: 'An identifier for the business, unique to the customer.<br><br>Must conform to the regular expression `^X[A-Z0-9]{1}IS[0-9]{11}$`'
        example: 'XBIS00000001319'
        required: false
  taxYearBroughtForwardFrom:
    queryParameters:
      taxYearBroughtForwardFrom:
        description: |
          The tax year to which the loss applies in the format YYYY-YY. The minimum tax year is 2018-19. The tax year must have ended.
          No gaps are allowed, for example, 2020-22 is not valid.<br><br>
          For 2023-24 and onwards, data must be requested individually by tax year.
        example: "2023-24"
        required: false
  taxYearClaimedFor:
    queryParameters:
      taxYearClaimedFor:
        description: |
          The tax year to which the claim applies in the format YYYY-YY.  The minimum tax year is 2019-20. No gaps are allowed. For example, 2020-22 is not valid.<br><br>
          For 2023-24 and onwards, data must be requested individually by tax year.
        example: "2023-24"
        required: false
  typeOfClaim:
    queryParameters:
      typeOfClaim:
        description: 'The type of claim to be applied.<br><br>Permitted values:<ul style = "list-style-type: none; padding: 0;"><li>`carry-sideways`'
        required: false