is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatLossId
  - errors.clientOrAgentNotAuthorised
  - errors.notFoundLossId
displayName: Retrieve a Brought Forward Loss
description: This endpoint allows a user to retrieve a single brought forward loss.
(annotations.sandboxData): !include scenarios/broughtForwardLosses_get.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
  200:
    body:
      application/json:
        type: !include schemas/broughtForwardLosses/retrieveBFLoss/retrieve_response.json
        examples:
          example-1:
            description: Self-employment Class 4 loss
            value: !include examples/broughtForwardLosses/retrieveBFLoss/retrieve_seClass4_response.json
          example-2:
            description: UK FHL property loss
            value: !include examples/broughtForwardLosses/retrieveBFLoss/retrieve_fhl_response.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.
