#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

traits:
  taxYearForClaims:
    queryParameters:
      taxYear:
        description: 'The tax year the data applies to, for example, 2019-20. The start year and end year must not span two tax years. No gaps are allowed, for example, 2019-21 is not valid. The minimum tax year is 2019-20.'
        example: "2019-20"
        required: false
  taxYearForBFLosses:
    queryParameters:
      taxYear:
        description: 'The tax year the data applies to, for example, 2018-19. The start year and end year must not span two tax years. No gaps are allowed, for example, 2018-20 is not valid. The minimum tax year is 2018-19.'
        example: "2018-19"
        required: false
  typeOfLossForClaims:
    queryParameters:
      typeOfLoss:
        description: 'The type of business the loss applies to. Limited to the following possible values: <b><ul><li>`self-employment`<li>`uk-property-non-fhl`</b>'
        required: false
  typeOfLossForBFLosses:
    queryParameters:
      typeOfLoss:
        description: 'The type of business the loss applies to. Limited to the following possible values: <b><ul><li>`self-employment`<li>`uk-property-fhl`<li>`uk-property-non-fhl`</b>'
        required: false
  selfEmploymentId:
    queryParameters:
      selfEmploymentId:
        description: 'Unique identifier of the income source the claim relates to. <b>Must conform to the regular expression <ul><li>`^X[A-Z0-9]{1}IS[0-9]{11}$` </b>'
        example: 'XGIS00000001319'
        required: false
  claimType:
    queryParameters:
      claimType:
        description: '[This query parameter is only available in Sandbox]<br/><br/>The type of loss claim. Limited to the following possible values: <ul><li><b>`carry-sideways`</b></li></ul>'
        required: false
        