#%RAML 1.0

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml
  errors: errors.raml
  headers: headers.raml
  queryParameters: queryParameters.raml

title: Individual Losses (MTD)
description: This is a spec for the Individual Losses API.
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: application/json

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include docs/errors.md
 - title: Changelog
   content: !include docs/changelog.md
 - title: Support
   content: !include docs/support.md
 - title: Testing
   content: !include docs/testing.md

'/individuals/losses':
  /{nino}:
    uriParameters:
      nino:
        description: National Insurance number, in the format AA999999A.
        type: string
        example: TC663795B
    /brought-forward-losses:
      (annotations.group):
        name: Brought Forward Losses
        description: !include docs/group_broughtForwardLosses.md
      post: !include broughtForwardLosses_create.raml
      get: !include broughtForwardLosses_list.raml
      /{lossId}:
        uriParameters:
          lossId:
            description: A unique identifier for the brought forward loss. <br><br>Must conform to the regular expression `^[A-Za-z0-9]{15}$`
            type: string
            example: "1234568790ABCDE"
        get: !include broughtForwardLosses_get.raml
        delete: !include broughtForwardLosses_delete.raml
        /change-loss-amount:
          post: !include broughtForwardLosses_amend.raml
    /loss-claims:
      (annotations.group):
        name: Loss Claims
        description: !include docs/group_lossClaims.md
      post: !include lossClaims_create.raml
      get: !include lossClaims_list.raml
      /{claimId}:
        uriParameters:
          claimId:
            description: A unique identifier for the loss claim. <br><br>Must conform to the regular expression `^[A-Za-z0-9]{15}$`
            type: string
            example: "AAZZ0123456789a"
        get: !include lossClaims_get.raml
        delete: !include lossClaims_delete.raml
        /change-type-of-claim:
          post: !include lossClaims_amend.raml
      /order:
        description:
        put: !include lossClaimsOrder_amend.raml

