#%RAML 1.0

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

title: Individual Losses (MTD)
description: This is a draft spec for the Individual Losses API.
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: application/json

traits:
  notFound:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: The matching resource is not found.
              value:
                code: MATCHING_RESOURCE_NOT_FOUND
  clientOrAgentNotAuthorised:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              clientOrAgentNotAuthorised:
                description: 'The client and/or agent is not authorised. This is normally because: the client is not subscribed to MTD, the agent is not subscribed to Agent Services, or the client has not authorised the agent to act on their behalf.'
                value:
                  code: CLIENT_OR_AGENT_NOT_AUTHORISED
  formatNino:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatNino:
                description: The provided NINO is invalid
                value:
                  code: FORMAT_NINO
  formatTaxYear:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatTaxYear:
                description: The provided tax year is invalid
                value:
                  code: FORMAT_TAX_YEAR
  incorrectOrEmptyBody:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              incorrectOrEmptyBody:
                description: An empty or non-matching body was submitted
                value:
                  code: RULE_INCORRECT_OR_EMPTY_BODY_SUBMITTED
  ruleTaxYearNotSupported:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              rule_TaxYearNotSupported:
                description: The specified tax year is not supported. That is, the tax year specified is before the minimum tax year value.
                value:
                  code: RULE_TAX_YEAR_NOT_SUPPORTED
  ruleTaxYearRangeExceeded:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleTaxYearRangeExceeded:
                description: Tax year range exceeded. A tax year range of one year is required.
                value:
                  code: RULE_TAX_YEAR_RANGE_EXCEEDED
  ruleInvalidIncomeSourceId:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleTypeOfClaim:
                description: The supplied income source ID is invalid.
                value:
                  code: RULES_INVALID_INCOME_SOURCE_ID
  formatLossType:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatLossType:
                description: The format of the loss type is not valid.
                value:
                  code: FORMAT_TYPE_OF_LOSS
  formatSelfEmploymentId:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatSelfEmploymentId:
                description: The format of the Self Employment ID is not valid.
                value:
                  code: FORMAT_SELF_EMPLOYMENT_ID
  ruleSelfEmploymentId:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleSelfEmploymentId:
                description: A self employment ID was supplied for a property business.
                value:
                  code: RULE_SELF_EMPLOYMENT_ID
  missingSelfEmploymentId:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              missingSelfEmploymentId:
                description: The self employment ID is missing.
                value:
                  code: MISSING_SELF_EMPLOYMENT_ID
  formatLossId:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatLossId:
                description: The format of the loss id is not valid.
                value:
                  code: FORMAT_LOSS_ID
  formatLossAmount:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatLossAmount:
                description: The format of the loss amount is not valid.
                value:
                  code: FORMAT_LOSS_AMOUNT
  ruleLossAmount:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleLossAmount:
                description: Amounts should be a positive number less than 99999999999.99 with up to 2 decimal places.
                value:
                  code: RULE_LOSS_AMOUNT
  ruleDuplicateLossAmount:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleDuplicateLossAmount:
                description: A previous amount was submitted for this tax year
                value:
                  code: RULE_DUPLICATE_???
  formatTypeOfClaim:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatTypeOfClaim:
                description: The format of the type of claim is not valid.
                value:
                  code: FORMAT_TYPE_OF_CLAIM
  ruleTypeOfClaim:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleTypeOfClaim:
                description: The type of Claim requested is not available for this type of loss.
                value:
                  code: RULE_TYPE_OF_CLAIM_INVALID
  formatClaimId:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatClaimId:
                description: The format of the supplied loss claim ID is not valid.
                value:
                  code: FORMAT_LOSS_CLAIM_ID

  contentTypeJson:
    headers:
      Content-Type:
        description: Specifies the format of the request body, which must be JSON.
        type: string
        required: true
        example: application/json
  acceptJson:
    headers:
      Accept:
        description: Specifies the response format and the version of the API to be used.
        type: string
        required: true
        example: 'application/vnd.hmrc.1.0+json'
  authorization:
    headers:
      Authorization:
        description: |
          An OAuth 2.0 Bearer Token with the <b>write:self-assessment</b> or <b>read:self-assessment</b> scope.
        type: string
        required: true
        example: Bearer bb7fed3fe10dd235a2ccda3d50fb
  testScenarioHeader:
    headers:
      Gov-Test-Scenario:
        description: Only in sandbox environment. See Test Data table for all header values.
        type: string
        required: false
        example: '-'

  taxYear:
    queryParameters:
      taxYear:
        description: 'The tax year the data applies to, for example, 2018-19. The start year and end year must not span two tax years. No gaps are allowed, for example, 2017-19 is not valid. The minimum tax year is 2016-17.'
        example: "2017-18"
        required: false
  lossType:
    queryParameters:
      lossType:
        description: 'The type of business the loss applies to. Limited to the following possible values: <b><ul><li>`self-employment`<li>`self-employment-class4`<li>`uk-fhl-property`<li>`uk-other-property`</b>'
        required: false
  typeOfLoss:
    queryParameters:
      typeOfLoss:
        description: 'The type of business the loss applies to. Limited to the following possible values: <b><ul><li>`self-employment`<li>`uk-fhl-property`<li>`uk-other-property`</b>'
        required: false
  selfEmploymentId:
    queryParameters:
      selfEmploymentId:
        description: 'Unique identifier of the income source the claim relates to.'
        example: 'XGIS00000001319'
        required: false


documentation:
  - title: Overview
    content: !include docs/overview.md
  - title: Changelog
    content: !include docs/changelog.md
  - title: Support
    content: !include docs/support.md
  - title: Testing
    content: !include docs/testing.md
  - title: Versioning
    content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
  - title: Errors
    content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md

'/individual/losses':
  /{nino}:
    uriParameters:
      nino:
        description: National Insurance number, in the format AA999999A.
        type: string
        example: TC663795B
    /brought-forward-losses:
      (annotations.group):
        name: Brought Forward Losses
        description: !include docs/group_broughtForwardLosses.md
      post: !include broughtForwardLosses_create.raml
      get: !include broughtForwardLosses_list.raml
      /{lossId}:
        uriParameters:
          lossId:
            description: A unique identifier for the brought forward loss.
            type: string
        get: !include broughtForwardLosses_get.raml
        delete: !include broughtForwardLosses_delete.raml
        /change-loss-amount:
          post: !include broughtForwardLosses_amend.raml
    /claims:
      (annotations.group):
        name: Loss Claims
        description: !include docs/group_lossClaims.md
      post: !include lossClaims_create.raml
      get: !include lossClaims_listAll.raml
      /{claimId}:
        uriParameters:
          claimId:
            description: A unique identifier for the loss claim.
            type: string
        get: !include lossClaims_get.raml
        delete: !include lossClaims_delete.raml
        /change-claim-type:
          post: !include lossClaims_amend.raml

