#%RAML 1.0

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  errors: errors.raml
  headers: headers.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

title: Individual Losses
description: |-
  This is a draft spec for the Individual Losses API.
version: 1.0.0

documentation:
  - title: Overview
    content: !include docs/overview.md
  - title: Changelog
    content: !include docs/changelog.md
  - title: Support
    content: !include docs/support.md
  - title: Testing
    content: !include docs/testing.md
  - title: Versioning
    content: !include https://www.tax.service.gov.uk/api-documentation/assets/common/docs/versioning.md
  - title: Errors
    content: !include https://www.tax.service.gov.uk/api-documentation/assets/common/docs/errors.md

'/losses/individual':
  /{nino}:
    uriParameters:
      nino:
        description: National Insurance number, in the format AA999999A.
        type: string
        example: TC663795B
    /brought-forward:  
      get: !include broughtForwardLosses_list.raml
      post: !include broughtForwardLosses_create.raml
      /{lossId}:
        uriParameters:
          lossId:
            description: A unique identifier for the brought forward loss.
            type: string
        get: !include broughtForwardLosses_get.raml
        delete: !include broughtForwardLosses_delete.raml
        /change-loss-amount:
          post: !include broughtForwardLosses_amend.raml
