is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTaxYear
  - errors.ruleTaxYearNotSupported
  - errors.ruleTaxYearRangeExceeded
  - errors.formatLossType
  - errors.formatSelfEmploymentId
  - errors.ruleSelfEmploymentId
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
  - queryParameters.taxYearBFLoss
  - queryParameters.typeOfLoss
  - queryParameters.selfEmploymentId
displayName: List Brought Forward Losses [test only]
description: This endpoint allows users to retrieve a list of all brought forward losses which they have incurred before joining MTD.
(annotations.sandboxData): !include scenarios/broughtForwardLosses_listAll.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
 200:
   body:
     application/json:
       type: !include schemas/broughtForwardLosses/listAllBFLoss/listAll_response.json
       example: !include examples/broughtForwardLosses/listAllBFLoss/listAll_response.json
   headers:
     X-CorrelationId:
       example: c75f40a6-a3df-4429-a697-471eeec46435
       description: Unique ID for operation tracking <br> String, 36 characters.
