#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml


traits:
  formatNino:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: The provided NINO is invalid
              value:
                code: FORMAT_NINO
  formatTaxYear:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: The provided tax year is invalid
              value:
                code: FORMAT_TAX_YEAR
  notFound:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: askdjhfs
              value:
                code: MATCHING_RESOURCE_NOT_FOUND
  unauthorised:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: blah blah blah
              value:
                code: CLIENT_OR_AGENT_NOT_AUTHORISED
  