#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml


traits:
  notFound:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: The matching resource is not found.
              value:
                code: MATCHING_RESOURCE_NOT_FOUND
  clientOrAgentNotAuthorised:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              clientOrAgentNotAuthorised:
                description: 'The client and/or agent is not authorised. This is normally because: the client is not subscribed to MTD, the agent is not subscribed to Agent Services, or the client has not authorised the agent to act on their behalf.'
                value:
                  code: CLIENT_OR_AGENT_NOT_AUTHORISED
  formatNino:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatNino:
                description: The provided NINO is invalid
                value:
                  code: FORMAT_NINO
  formatTaxYear:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatTaxYear:
                description: The provided tax year is invalid
                value:
                  code: FORMAT_TAX_YEAR
  incorrectOrEmptyBody:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: An empty or non-matching body was submitted
              value:
                code: RULE_INCORRECT_OR_EMPTY_BODY_SUBMITTED
  rule_TaxYearNotSupported:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: The specified tax year is not supported. That is, the tax year specified is before the minimum tax year value.
              value:
                code: RULE_TAX_YEAR_NOT_SUPPORTED
  ruleTaxYearRangeExceeded:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Tax year range exceeded. A tax year range of one year is required.
              value:
                code: RULE_TAX_YEAR_RANGE_EXCEEDED
  formatLossType:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: The format of the loss type is not valid.
              value:
                code: FORMAT_TYPE_OF_LOSS
  formatSelfEmploymentId:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: The format of the Self Employment ID is not valid.
              value:
                code: FORMAT_SELF_EMPLOYMENT_ID
  ruleSelfEmploymentId:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: A self employment ID was supplied for a property business.
              value:
                code: RULE_SELF_EMPLOYMENT_ID
  formatLossId:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: The format of the loss id is not valid.
              value:
                code: FORMAT_LOSS_ID
  formatLossAmount:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: The format of the loss amount is not valid.
              value:
                code: FORMAT_LOSS_AMOUNT
  ruleLossAmount:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: Amounts should be a positive number less than 99999999999.99 with up to 2 decimal places.
              value:
                code: RULE_LOSS_AMOUNT
  ruleDuplicateLossAmount:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: A previous amount was submitted for this tax year
              value:
                code: RULE_DUPLICATE_???