is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatClaimId
  - errors.clientOrAgentNotAuthorised
  - errors.notFoundClaimId
displayName: Retrieve a Loss Claim
description: This endpoint allows the user to retrieve the detail of an existing loss claim.
(annotations.sandboxData): !include scenarios/lossClaims_get.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
  200:
    body:
      application/json:
        type: !include schemas/lossClaims/retrieveClaim/retrieve_response.json
        examples:
          example-1:
            description: Self-employment claim
            value: !include examples/lossClaims/retrieveClaim/retrieve_se_response.json
          example-2:
            description: UK Non-FHL property claim
            value: !include examples/lossClaims/retrieveClaim/retrieve_non_fhl_response.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.
