is:
  - headers.acceptJson
  - headers.contentTypeJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.incorrectOrEmptyBody
  - errors.formatLossType
  - errors.formatSelfEmploymentId
  - errors.ruleSelfEmploymentId
  - errors.formatTypeOfClaim
  - errors.ruleTypeOfClaim400
  - errors.formatTaxYear
  - errors.ruleTaxYearNotSupported
  - errors.ruleTaxYearRangeInvalid
  - errors.rulePeriodNotEnded
  - errors.ruleDuplicateClaimSubmission
  - errors.clientOrAgentNotAuthorised
  - errors.notFoundIncomeSource
  - errors.ruleNoAccountingPeriod
displayName: Create a Loss Claim [No longer available]
description: This resource is no longer available. It has been replaced by the Create a Loss Claim endpoint in the <a href="https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individual-losses-api/2.0">individual-losses-api v2.0</a>.
(annotations.sandboxData): !include scenarios/lossClaims_create.md
(annotations.scope): "write:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
body:
  application/json:
    type: !include schemas/lossClaims/createClaim/create_request.json
    examples:
      example-1:
        description: Self-employment claim
        value: !include examples/lossClaims/createClaim/create_se_request.json
      example-2:
        description: UK Non-FHL Property claim
        value: !include examples/lossClaims/createClaim/create_non_fhl_request.json
responses:
  201:
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.
    body:
      application/json:
        type: !include schemas/lossClaims/createClaim/create_response.json
        example: !include examples/lossClaims/createClaim/create_response.json
