#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

traits:
  taxYear:
    queryParameters:
      taxYear:
        description: 'The tax year the data applies to, for example, 2018-19. The start year and end year must not span two tax years. No gaps are allowed, for example, 2017-19 is not valid. The minimum tax year is 2016-17.'
        example: "2017-18"
        required: false
  lossType:
    queryParameters:
      lossType:
        description: 'The type of business the loss applies to. Limited to the following possible values: <b><ul> <li> self-employment  <li>self-employment-class4  <li>uk-fhl-property   <li>uk-other-property </b>'
        example: "self-employment"
        required: false
